/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/characters` | `/characters`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/projects` | `/projects`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stories` | `/stories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/videos` | `/videos`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/character/create`; params?: Router.UnknownInputParams; } | { pathname: `/story/create`; params?: Router.UnknownInputParams; } | { pathname: `/video/generate`; params?: Router.UnknownInputParams; } | { pathname: `/character/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/story/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/characters` | `/characters`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/projects` | `/projects`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stories` | `/stories`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/videos` | `/videos`; params?: Router.UnknownOutputParams; } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/character/create`; params?: Router.UnknownOutputParams; } | { pathname: `/story/create`; params?: Router.UnknownOutputParams; } | { pathname: `/video/generate`; params?: Router.UnknownOutputParams; } | { pathname: `/character/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/story/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/characters${`?${string}` | `#${string}` | ''}` | `/characters${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/projects${`?${string}` | `#${string}` | ''}` | `/projects${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stories${`?${string}` | `#${string}` | ''}` | `/stories${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/videos${`?${string}` | `#${string}` | ''}` | `/videos${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `/character/create${`?${string}` | `#${string}` | ''}` | `/story/create${`?${string}` | `#${string}` | ''}` | `/video/generate${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/characters` | `/characters`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/projects` | `/projects`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stories` | `/stories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/videos` | `/videos`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/character/create`; params?: Router.UnknownInputParams; } | { pathname: `/story/create`; params?: Router.UnknownInputParams; } | { pathname: `/video/generate`; params?: Router.UnknownInputParams; } | `/character/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/story/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/character/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/story/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
