import { buildFluxTask, buildGptImage2Task, buildSeedreamTask, buildVideoTask, previewSummary } from './payloads.js';
import { checkKlingMarketplace, createTask, getCredits, getTask, rehostKlingPayload } from './kie-client.js';
import { databaseHealth, getJob, getProduct, listJobs, listProducts, recordJob, upsertProduct } from './database.js';

const read={readOnlyHint:true,openWorldHint:true,destructiveHint:false,idempotentHint:true};
const renderAnn={readOnlyHint:false,openWorldHint:true,destructiveHint:false,idempotentHint:false};
const file={type:'object',required:['download_url','file_id'],properties:{download_url:{type:'string',format:'uri'},file_id:{type:'string'},mime_type:{type:'string'},file_name:{type:'string'}},additionalProperties:true};
const refs=(n)=>Object.fromEntries(Array.from({length:n},(_,i)=>[`reference_image_${i+1}`,file]));
const r4=refs(4),r8=refs(8);
const img={prompt:{type:'string',minLength:3,maxLength:5000},...r8,aspect_ratio:{type:'string',enum:['1:1','4:3','3:4','16:9','9:16','3:2','2:3']},product_id:{type:'string'}};
const vid={prompt:{type:'string',minLength:3,maxLength:5000},model:{type:'string',enum:['grok_imagine_video_1_5','seedance_2_fast','seedance_2_mini','kling_3_0']},start_frame:file,last_frame:file,...r4,aspect_ratio:{type:'string',enum:['9:16','16:9','1:1']},resolution:{type:'string',enum:['480p','720p']},duration:{type:'integer',minimum:4,maximum:15},generate_audio:{type:'boolean'},seedance_reference_mode:{type:'string',enum:['first_frame','multimodal']},kling_mode:{type:'string',enum:['std','pro','4K']},kling_multi_shots:{type:'boolean'},kling_multi_prompt:{type:'array',items:{type:'object'}},element_name:{type:'string'},element_description:{type:'string'},product_id:{type:'string'}};
const s=(properties,required=[])=>({type:'object',properties,required,additionalProperties:false});
export const tools=[
{name:'check_kie_credits',description:'Verify KIE connection and remaining credits. No render.',inputSchema:s({}),annotations:read},
{name:'check_kling3_available',description:'Check KIE auth and Kling 3.0 availability. No render.',inputSchema:s({}),annotations:read},
{name:'prepare_kie_render',description:'Validate exact KIE payload without generation credits.',inputSchema:s({kind:{type:'string',enum:['gpt_image_2','flux_2_pro','seedream_5_lite','video']},...img,...vid},['kind','prompt']),annotations:{...read,openWorldHint:false},_meta:{'openai/fileParams':['start_frame','last_frame',...Object.keys(r8)]}},
{name:'render_gpt_image_2',description:'GPT Image 2 renderer. Requires confirm_render=true and spends KIE credits.',inputSchema:s({...img,confirm_render:{const:true}},['prompt','confirm_render']),annotations:renderAnn,_meta:{'openai/fileParams':Object.keys(r8)}},
{name:'render_flux2_pro_image',description:'Flux 2 Pro renderer. Only when explicitly requested. Requires confirm_render=true.',inputSchema:s({...img,confirm_render:{const:true}},['prompt','confirm_render']),annotations:renderAnn,_meta:{'openai/fileParams':Object.keys(r8)}},
{name:'render_seedream5_lite_image',description:'Seedream 5 Lite renderer. Only when explicitly requested. Requires confirm_render=true.',inputSchema:s({...img,confirm_render:{const:true}},['prompt','confirm_render']),annotations:renderAnn,_meta:{'openai/fileParams':Object.keys(r8)}},
{name:'render_kie_video',description:'Video renderer. Default Grok 1.5; Seedance and Kling 3.0 optional. Requires confirm_render=true.',inputSchema:s({...vid,confirm_render:{const:true}},['prompt','confirm_render']),annotations:renderAnn,_meta:{'openai/fileParams':['start_frame','last_frame',...Object.keys(r4)]}},
{name:'check_kie_render',description:'Read render progress/result. No new render.',inputSchema:s({task_id:{type:'string',minLength:3}},['task_id']),annotations:read},
{name:'save_product_cheat',description:'Store/update verified product facts and visual locks. No render.',inputSchema:s({product_id:{type:'string'},name:{type:'string'},brand:{type:'string'},variant:{type:'string'},verified_facts:{type:'array',items:{type:'string'}},visual_locks:{type:'array',items:{type:'string'}},allowed_claims:{type:'array',items:{type:'string'}},forbidden_claims:{type:'array',items:{type:'string'}},reference_notes:{type:'string'},source_urls:{type:'array',items:{type:'string',format:'uri'}}},['product_id','name']),annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false,idempotentHint:true}},
{name:'get_product_cheat',description:'Load one product cheat. No render.',inputSchema:s({product_id:{type:'string'}},['product_id']),annotations:{...read,openWorldHint:false}},
{name:'list_product_cheats',description:'List stored product cheats. No render.',inputSchema:s({}),annotations:{...read,openWorldHint:false}},
{name:'list_kie_jobs',description:'List recent KIE jobs. No render.',inputSchema:s({limit:{type:'integer',minimum:1,maximum:100}}),annotations:{...read,openWorldHint:false}},
{name:'check_lyra_v2',description:'System check for Lyra V2, models and database. No render.',inputSchema:s({}),annotations:{...read,openWorldHint:false}}
];
const out=(t,d={})=>({content:[{type:'text',text:t}],structuredContent:d});
const fail=(e)=>({isError:true,content:[{type:'text',text:e instanceof Error?e.message:String(e)}]});
const confirm=(a)=>{if(a.confirm_render!==true)throw new Error('Render nicht bestätigt. confirm_render=true ist erforderlich.');};
async function submit(body,a){const creditsBefore=await getCredits();const send=body.model==='kling-3.0/video'?await rehostKlingPayload(body):body;const taskId=await createTask(send);await recordJob({task_id:taskId,product_id:a.product_id??null,model:body.model,prompt:a.prompt,state:'submitted',credits_before:creditsBefore,payload_summary:previewSummary(body)});return{taskId,creditsBefore};}
export async function callTool(name,a={}){try{
if(name==='check_kie_credits'){const c=await getCredits();return out(`KIE verbunden. Credits: ${JSON.stringify(c)}. Kein Render gestartet.`,{connected:true,credits_remaining:c,render_started:false});}
if(name==='check_kling3_available'){const[c,m]=await Promise.all([getCredits(),checkKlingMarketplace()]);return out(`KIE-Auth OK. Kling 3.0 Marketplace: ${m.available?'verfügbar':'nicht bestätigt'}. Kein Render gestartet.`,{kie_authenticated:true,credits_remaining:c,kling3_marketplace_available:m.available,model_id:'kling-3.0/video',render_started:false});}
if(name==='prepare_kie_render'){let b;if(a.kind==='gpt_image_2')b=buildGptImage2Task(a);else if(a.kind==='flux_2_pro')b=buildFluxTask(a);else if(a.kind==='seedream_5_lite')b=buildSeedreamTask(a);else b=buildVideoTask(a);const w=[];if(a.model==='kling_3_0'&&a.kling_mode==='4K')w.push('Kling 4K ist teurer als PRO; nur bewusst verwenden.');return out(`Dry-Run gültig: ${previewSummary(b)}. Kein Render gestartet, keine Generation-Credits verbraucht.`,{valid:true,model:b.model,payload:b,defaults_summary:previewSummary(b),warnings:w,generation_started:false,credits_spent:false});}
if(['render_gpt_image_2','render_flux2_pro_image','render_seedream5_lite_image'].includes(name)){confirm(a);const build=name==='render_gpt_image_2'?buildGptImage2Task:name==='render_flux2_pro_image'?buildFluxTask:buildSeedreamTask;const b=build(a);const r=await submit(b,a);return out(`Render gestartet: ${r.taskId}.`,{task_id:r.taskId,model:b.model,state:'submitted',credits_before:r.creditsBefore});}
if(name==='render_kie_video'){confirm(a);const b=buildVideoTask(a);const r=await submit(b,a);return out(`KIE-Video gestartet: ${r.taskId}. Modell: ${b.model}.`,{task_id:r.taskId,model:b.model,state:'submitted',credits_before:r.creditsBefore});}
if(name==='check_kie_render'){const t=await getTask(a.task_id);const k=await getJob(a.task_id);await recordJob({...k,task_id:a.task_id,...t});return out(t.state==='success'?`Render fertig: ${t.result_urls.join(' ')}`:t.state==='fail'?`Render fehlgeschlagen: ${t.error_message??t.error_code??'unbekannt'}`:`Renderstatus: ${t.state}.`,t);}
if(name==='save_product_cheat'){const p=await upsertProduct(a),d=await databaseHealth();return out(`Produkt-Cheat ${p.product_id} gespeichert. DB persistent: ${d.persistent?'ja':'noch nicht'}.`,{product:p,database:d});}
if(name==='get_product_cheat'){const p=await getProduct(a.product_id);return out(p?JSON.stringify(p):`Kein Produkt-Cheat für ${a.product_id} gefunden.`,{product:p});}
if(name==='list_product_cheats'){const p=await listProducts(),d=await databaseHealth();return out(`${p.length} Produkt-Cheats gefunden. DB persistent: ${d.persistent?'ja':'noch nicht'}.`,{products:p,database:d});}
if(name==='list_kie_jobs'){const j=await listJobs(a.limit??20);return out(`${j.length} Jobs gefunden.`,{jobs:j});}
if(name==='check_lyra_v2'){const d=await databaseHealth();return out(`Lyra V2 2.1.1 bereit. Bilder: GPT Image 2, Flux 2 Pro, Seedream 5 Lite. Videos: Grok 1.5, Seedance Fast/Mini, Kling 3.0. DB persistent: ${d.persistent?'ja':'noch nicht'}. Kein Render gestartet.`,{ok:true,version:'2.1.1',database:d,image_models:['GPT Image 2','Flux 2 Pro','Seedream 5 Lite'],video_models:['Grok Imagine Video 1.5','Seedance 2 Fast','Seedance 2 Mini','Kling 3.0'],render_started:false});}
throw new Error(`Unbekanntes Tool: ${name}`);
}catch(e){return fail(e);}}
